### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by perencia** [rii-mango/JPEGLosslessDecoderJS#12]
Tests did not pass.

```
pedro@debian:~/node_modules/jpeg-lossless-decoder-js$ npm test

> jpeg-lossless-decoder-js@2.0.2 test /home/pedro/node_modules/jpeg-lossless-decoder-js
> mocha tests


/home/pedro/node_modules/jpeg-lossless-decoder-js/src/decoder.js:137
        throw new Error("Not a JPEG file");
              ^
Error: Not a JPEG file
    at jpeg.lossless.Decoder.decode (/home/pedro/node_modules/jpeg-lossless-decoder-js/src/decoder.js:137:15)
    at Object.<anonymous> (/home/pedro/node_modules/jpeg-lossless-decoder-js/tests/driver-sel1-oldapi.js:33:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/pedro/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/pedro/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/home/pedro/node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/home/pedro/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm ERR! Test failed.  See above for more details.
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

**Comment by perencia** [comment]
The problem is in ```data-stream.js``` constructor, creating the Uint8Array without offset and length requires to not pass the parameters instead of passing them as undefined. I attach a patch, but maybe ```driver-sel1-oldapi.js``` should just be removed altogether.

```
+++ data-stream.js	2017-08-19 23:38:01.258974864 +0200
@@ -40,9 +40,13 @@
 
 /*** Constructor ***/
 jpeg.lossless.DataStream = jpeg.lossless.DataStream || function (data, offset, length) {
-    // Note: DataView is much slower than Int8Array
-    // this.buffer = new DataView(data, offset, length);
-    this.buffer = new Uint8Array(data, offset, length);
+    if (offset === undefined && length === undefined) { // Old api
+        // Note: DataView is much slower than Int8Array
+        // this.buffer = new DataView(data, offset, length);
+        this.buffer = new Uint8Array(data);
+    } else {
+       this.buffer = new Uint8Array(data, offset, length);
+    }
     this.index = 0;
 };
 
```

**Comment by martinezmj-ims** [comment]
Strange, is it dependent of the version of node.js or the platform?  Running node.js v4.2.4 on macOS doesn't produce the error.  Thanks for catching that.  I've patched that file.

**Comment by perencia** [comment]
I was using a somewhat old version of nodejs, 0.10.29. Is the version available on the debian jessie's repos.
